### ISSUE TITLE
Error in example file shipments_rates.php

### ISSUE THREAD

**Issue by David263** [EasyPost/easypost-php#101]
In example file https://github.com/EasyPost/easypost-php/blob/master/examples/shipments_rates.php, the lines

```
// create rates the other way
$created_rates = \EasyPost\Rate::create($shipment);
print_r($created_rates);
```
generate this error message:

`Fatal error: Uncaught Error: Call to undefined method EasyPost\Rate::create() in C:\Web\easypost-test\test.php:64 Stack trace: #0 {main} thrown in C:\Web\easypost-test\test.php on line 64
`

**Comment by Justintime50** [comment]
Hey @David263, I apologize for the error! The functionality expressed in that example does not work this way. I've submitted PR #102 to address this. With this client library, you can only retrieve a rate. To properly rate a shipment, you'd want to [create the shipment](https://www.easypost.com/docs/api/php#shipments-create-codesample) and if there are no rating errors, there will be a rates object on the returned shipment where you can then purchase the shipment using one of those rates.
