### ISSUE TITLE
Undefined $v while deleting a carrierAccount from a child user

### ISSUE THREAD

**Issue by dev-support-t2** [EasyPost/easypost-php#106]
Good day,

      when i run this function on a carrierAccount within the delete carrierAccount process, it does return me an error :

`Undefined variable: v [ROOT/vendor/easypost/easypost-php/lib/EasyPost/EasyPostObject.php, line 124]`

I think it is because you unset the values and then go looping trough all the keys and their values recursively bu you have their are already unset.

`
    /**
     * unset magic method
     *
     * @param string $k
     */
    public function __unset($k)
    {
        if (!in_array($k, $this->_immutableValues)) {
            unset($this->_values[$k]);

            $i = 0;
            $current = $this;
            $param = array($k => $v);
            while (true && $i < 99) {
                if (!is_null($current->_parent)) {
                    $param = array($current->_name => $param);
                    $current = $current->_parent;
                } else {
                    reset($param);
                    $first_key = key($param);
                    unset($current->_unsavedValues[$first_key]);
                    break;
                }
                $i++;
            }
        }
    }
`
Thanks and have a nice day !

Francis

**Comment by Justintime50** [comment]
Hey @dev-support-t2, thanks for reporting this!

What version of this library are you using? I believe this was patched recently (see #87) and should no longer be a problem in the most recent versions of this library. Can you try updating and let me know if it's still an issue?

**Comment by dev-support-t2** [comment]
Fixed!
Thanks for the fast response!
