### ISSUE TITLE
EasyPost API Not Updating Until Hitting track.easypost.com

### ISSUE THREAD

**Issue by mwrouse** [EasyPost/easypost-php#107]
> I realize this is not a direct issue with the PHP library. However, I am using the PHP library as my library, so I am opening it here.

### The Issue
The issue I have noticed is that `\EasyPost\Tracker::retrieve` will occasionally return out-dated information (sometimes up to 8 hours old based on the Last Updated Time). Then I visit the `track.easypost.com` url, then suddenly calling `retrieve` returns the latest information.

Here is a video demonstrating the problem: 
https://www.youtube.com/watch?v=niUJY4HHQVk
(In the video I talk about opening a private window. Apparently that window was invisible to the screen recorder. But it is not a cache issue).

In the video I show my website, that is a simple PHP script calling `retrieve` to get tracking information. I also show that the EasyPost dashboard is showing the same information. 
I open up the Public URL (`track.easypost.com`) for that tracker, and suddenly when I go back and refresh my page, I get the _actual latest information_. And it is now updated, and based on the time stamps it was almost 8 hours.

### Debugging
I am able to reproduce this in the NodeJS library as well. So it's not related to the PHP library at all (as I mentioned) but appears to be something with the actual EasyPost service.

In another video: https://www.youtube.com/watch?v=fXGmIDrxayQ (this used a throwaway API key, don't worry).
I show the same thing in the NodeJS library.
You can clearly see that it appears that the `track.easypost.com` page is doing something extra. 

In the second video there are no new tracking updates, but visiting `track.easypost.com` changes the last updated timestamp. This, of course, is not really a concern. In the first video is my real concern how it was over 8 hours and that updated information hadn't shown.

### Questions
1. Why does visiting `track.easypost.com` cause my API calls to return new information?
2. Is the `track.easypost.com` page doing something special? (i.e., why does it occasionally update the last-updated timestamp to the exact time? [the second video])

___
**Weird, and maybe related**
This is also interesting, watch my first video (https://www.youtube.com/watch?v=niUJY4HHQVk), around 0:40 when I visit track.easypost.com for the first time. 

It says "Getting the Latest Information," but it actually renders the OLD information. I then have to refresh with F5 and the new information is there.

This makes me wonder, if the EasyPost DB has the "latest" information, where is that page getting the old information? 

___
**A Note About EasyPost Support**
I have gone through EasyPost support for this problem, but they keep giving me the run-around about how I _need_ to be using webhooks to get the latest information (that would be absurd if true), and feeding me lines copied-and-pasted from the API documentation.

But most of all, they aren't actually answering my questions (beyond "clear your cache" BS), or even acknowledging that this could be a potential issue, and making no attempts to reproduce.

I just want some clear answers, and if it is an actual problem on your end then I want to get it seen by someone.

**Comment by mwrouse** [comment]
I have a cron job running every 30 minutes to send out emails when a package is delivered. So I've had emails go out at midnight because it took so long for my `retrieve` API calls to actually get the latest information (the package was delivered at like 1pm). That's _crazy_ considering you poll USPS every 30 minutes when the package is out for delivery (according to EasyPost Support)!

I realize that part can be done with webhooks. But having a webhook and my storing in my DB is overkill for my tracking page. You're already doing all of that, so a webhook would be of no benefit to me.


So even if this turns out to be something I'm doing wrong (I don't think so at this point), I need a solution. EasyPost Support has failed to realize that I potentially have an actual problem here.

**Comment by LoganSimonsen** [comment]
Hi @mwrouse,

I'm sorry to hear you are having this issue, but it is an issue directly related to EasyPost API functionality and is therefore not appropriate for this forum. 

I can tell you that there are certain situations where trackers may become "stale" for a period of time and visiting the tracking URL or making an API request will trigger a new update for that tracker. EasyPost has complex logic for each carrier that dictates how often we pull updates. The reason for this is that carriers often limit us on how many times we can make queries per day or per hour etc. Some of the limitations are unavoidable, but if you continue to work with support they will be able to investigate any instances that you feel are a problem.

In the future, please do not use public Github repositories in this manner. 

Thanks,
Logan Simonsen

**Comment by mwrouse** [comment]
Logan, 

As I clearly stated multiple times I know this is not a direct issue with this library, you do not need to explain to me how to use Github repositories or issues.

I appreciate you actually (partially) addressing my questions. Instead of being helpful you have chosen to be condescending, thanks for that.

But, when your support team is incredibly unhelpful and there are no other channels of reporting issues, we get to this point. Where else am I supposed to go?

You say:
> I can tell you that there are certain situations where trackers may become "stale" for a period of time and visiting the tracking URL or **making an API request** will trigger a new update for that tracker. 

Except it doesn't, I demonstrated that in my first video. The only way for me to get the new information is to wait a crazy long time, or visit the public url.

It has been 2 weeks now messaging your support team, and not once have they actually addressed my questions, or attempted to look into this issue. And _it is an issue_, despite you saying that it is "unavoidable."


Unfortunately, this experience has pushed me away from using EasyPost.
