### ISSUE TITLE
Address doesn't update the attribute

### ISSUE THREAD

**Issue by we4tech** [EasyPost/easypost-php#11]
Hi There,

I was trying to edit an existing address object, but it didn't work out. I assume this might be the reason - https://github.com/EasyPost/easypost-php/blob/master/lib/EasyPost/Resource.php#L105

As this is a hash map $k returns the value instead of the key. 

Please let me know if I am missing something.

Best wishes

**Comment by sawyer** [comment]
2.1.0 deals with unsavedValues in a saner way, however address objects are still immutable. If we decide to make them mutable in the future you would be able to edit their attributes and then call save().
