### ISSUE TITLE
Error when trying to buy USPS postage with version 4.0.1

### ISSUE THREAD

**Issue by klaxian** [EasyPost/easypost-php#117]
After upgrading to PHP SDK version 4.0.1, we are getting following error when any shipper tries to purchase USPS postage. Other carriers have not been affected. I think this might have to do with the switch to sending JSON payloads in version 4.0+. Can you please patch this bug asap? The latest PHP SDK versions are unusable in their current state. Thanks.

> Error parsing input.

**Comment by Justintime50** [comment]
- Please proved us a code snippet so we can attempt to reproduce the issue.

**Comment by fiendish** [comment]
But the same request works for other carriers?

**Comment by klaxian** [comment]
Yes, so far we only get the error when attempting to purchase USPS labels. UPS, FedEx, and others work normally.
