### ISSUE TITLE
[Bug]: unable to retrieve purchased shipment

### ISSUE THREAD

**Issue by jp92004** [EasyPost/easypost-php#164]
### Software Version

5.0

### Language Version

8.1

### Operating System

Linux

### What happened?

This worked fine until I upgraded the php library from 3.6 to 5.0.
When I attempt to retrieve a purchased shipment for a refund it causes a fatal error on this method:

$shipment = \EasyPost\Shipment::retrieve($epid);

This method works fine before I purchase the shipment.

### What was expected?

I would expect it to return an object.

### Sample Code

```inc
$shipment = \EasyPost\Shipment::retrieve($epid);
```

### Relevant logs

```sh
Fatal error: Uncaught Error: Class "\EasyPost\TrackingDetail" not found in /home/public_html/libs/easypost/lib/EasyPost/EasyPostObject.php:176 Stack trace: #0 /home/public_html/libs/easypost/lib/EasyPost/Util.php(144): EasyPost\EasyPostObject::constructFrom() #1 /home/public_html/libs/easypost/lib/EasyPost/Util.php(131): EasyPost\Util::convertToEasyPostObject() #2 /home/public_html/libs/easypost/lib/EasyPost/EasyPostObject.php(215): EasyPost\Util::convertToEasyPostObject() #3 /home/public_html/libs/easypost/lib/EasyPost/EasyPostObject.php(177): EasyPost\EasyPostObject->refreshFrom() #4 /home/public_html/libs/easypost/lib/EasyPost/Util.php(144): EasyPost\EasyPostObject::constructFrom() #5 /home/public_html/libs/easypost/lib/EasyPost/EasyPostObject.php(215): EasyPost\Util::convertToEasyPostObject() #6 /home/public_html/libs/easypost/lib/EasyPost/EasypostResource.php(77): EasyPost\EasyPostObject->refreshFrom() #7 /home/public_html/libs/easypost/lib/EasyPost/EasypostResource.php(113): EasyPost\EasypostResource->refresh() #8 /home/public_html/libs/easypost/lib/EasyPost/Shipment.php(49): EasyPost\EasypostResource::_retrieve() #9 /home/public_html/orders/order_shipping_void.php(12): EasyPost\Shipment::retrieve() #10 {main} thrown in /home/public_html/libs/easypost/lib/EasyPost/EasyPostObject.php on line 176
```

**Comment by nwithan8** [comment]
Thanks for reporting this error. We're trying to reproduce it on our end.

Can you do us a favor and see if the following file exists on your system?
`/home/public_html/libs/easypost/lib/EasyPost/TrackingDetail.php`

**Comment by jp92004** [comment]
Hey Nate! Thanks for your help. I do have that file, and it's contents are the same as the source here on github.

**Comment by Justintime50** [comment]
@jp92004 based on your earlier info it looks like you are requiring the files directly instead of using `composer` is that correct?

Can you help me understand how you downloaded/installed and finally required the library so we can reproduce? I'm unable to reproduce at the moment without additional details.

**Comment by jp92004** [comment]
That's correct. Just downloaded directly from github, 
require_once("../libs/easypost/lib/easypost.php");

Seems to work fine for creating shipments, retrieving a shipment, then purchasing the shipment. This is how I did it under the older version. Are there additional external dependencies between 3.6 and 5? I've perhaps missed a step.

**Comment by Justintime50** [comment]
I was able to reproduce this issue when requiring the library manually, thanks for reporting! We'll be releasing a patch version here shortly, please upgrade once that is out and you should be on your way!

I'd also highly recommend using `composer` if it is possible in your workflow to install our library.

**Comment by jp92004** [comment]
Hey awesome! Thank you to the both of you for looking into this so quickly. I'll keep an eye out for an update and download again, and I'll look into composer for the future. Thank you again!

**Comment by Justintime50** [comment]
This was just released via https://github.com/EasyPost/easypost-php/releases/tag/v5.1.1.

Thanks again for reporting this!
