### ISSUE TITLE
[Feat]: EasyPost\Error: A duplicate request is currently in-flight in (How to handle?)

### ISSUE THREAD

**Issue by iLoveSarabear** [EasyPost/easypost-php#179]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Hello, we receive this error for Fedex tracking numbers only.
`EasyPost\Error: A duplicate request is currently in-flight in`

Ex: 776734375340 (Fedex)

We're unable to create a tracker, or pull any tracking data. It's also happening a lot (But only for Fedex) How do we get around this kind of scenario as we're not sure if it's a bug, or if we simply need to call something to retrieve its tracking information.

Thanks.

**Comment by Justintime50** [comment]
Hey there, can you provide some additional details? What exactly were you doing when you received this error?

Typically this error is due to two things happening at the same time (such as multithreaded/concurrent requests). If you try to create the same object at the same time this could happen. The more info you can provide, the better we can assist you. Thanks!

**Comment by iLoveSarabear** [comment]
Hi Justin, we're just sending a request to EasyPost like any other day. There are no multithreaded or concurrent requests.

Try submitting that tracking number, it appears to only be Fedex tracking numbers that get stuck in the pipe.

Thanks

**Comment by Justintime50** [comment]
Ok, I was able to reproduce the issue. When running the following, I get the same error:

```php
    $tracker = \EasyPost\Tracker::create([
        "tracking_code" => "776734375340",
    ]);
```

However, when I explicitly pass the expected carrier with it, the tracker gets created correctly:

```php
    $tracker = \EasyPost\Tracker::create([
        "tracking_code" => "776734375340",
        "carrier" => "FedEx",
    ]);
```

It appears that this tracking number is valid with more than one carrier and so our tracking system attempt to create a tracker with multiple carriers leading to the error you received. If you explicitly pass the carrier it should be associated with, our system will only create it with that carrier. Our tracking system does its best to match known tracking patterns to carriers; however, many carriers share similar patterns and sometimes even the exact same tracking numbers. Per our docs:

> If no carrier is provided, EasyPost will attempt to determine the carrier based on the tracking_code provided. Providing a carrier parameter is recommended, since some tracking_codes are ambiguous and may match with more than one carrier. In addition, not having to auto-match the carrier will significantly speed up the response time.

My recommendation would be to always pass a carrier if available to avoid this issue. If you have additional API usage questions, please reach out to our rockstar support team at support@easypost.com.
