### ISSUE TITLE
How to access rates?

### ISSUE THREAD

**Issue by amilajack** [EasyPost/easypost-php#18]
I'm trying to access the rates created when initializing a shipment.

I currently have the following:

```
// This shows the variables
print_r($shipment->rates);

// This does not return them
return $shipment->rates;
```

can you please show me how to access them? Thanks!

**Comment by cheat117** [comment]
print($shipment->rates) may be what you are looking for.

Any Easypost object is printed as JSON.

**Comment by amilajack** [comment]
I see. Is there a way that I can store the rates in a variable?

**Comment by cheat117** [comment]
Are you looking to store them as an array? $shipment->rates is the property that holds the array of rates, so you should just be able to use that.
