### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by kirankspl** [EasyPost/easypost-php#19]
This Error Produced for One shipment when  $shipment->buy($shipment->rates[$index]); triggered
Error: undefined method `+' for nil:NilClass

I tried to debug the issue but no luck as it is a response from API with 422 response code. How to resolve this issue and what was the issue?

**Comment by att14** [comment]
Can you give more detail? What is the shipment id? What was the backtrace? How can I reproduce this issue?
