### ISSUE TITLE
Request for shipping methods takes for ever

### ISSUE THREAD

**Issue by MattSich** [EasyPost/easypost-php#20]
Not sure if this is something wrong with the php api or the service itself but it takes  a heck of a long time to load the shipping methods. took me over 1.5 minutes just a few seconds ago.

**Comment by MattSich** [comment]
Found the answer in the FAQ

**Comment by gsinkin** [comment]
Wow, 1.5min should never happen. For which carriers were you requesting rates? Mind sharing a sample request?

**Comment by MattSich** [comment]
@gsinkin will debug it further tonight and get you more info. I'm using a php back-end to make the request and angular on the front end. I think what happens is angular times out or something because I get an error about Access control which I never get without the easypost request - and this happens anywhere between 1.5s and 2.5s. Will get more info tonight

**Comment by gsinkin** [comment]
Aha.

Are you making a request from the client/browser direct to EasyPost? Have a look at CORS:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

We highly recommend making calls to EasyPost from your backend/server side.

Let me know what you find.

Thanks!

Gabe

**Comment by MattSich** [comment]
@gsinkin no it's happening on my backend. I'm using php as a backend API. I'll let you know when I get to it after work

**Comment by MattSich** [comment]
@gsinkin so it just keeps going honestly. I've been waiting for a few minutes now. Sometimes it's fast and sometimes it just takes for ever. 

Here's my code:
```
<?php

include(dirname(__FILE__). "/../helpers/API.php");
	
	$shipment = \EasyPost\Shipment::create(array(
	  'to_address' => array(
	    'name' => "Matt Sich",
	    'street1' => "12567 Summit Manor Dr",
	    'city' => "Fairfax",
	    'state' => "VA",
	    'zip' => "22033"
	  ),
	  'from_address' => array(
	    'company' => 'PhantomWeights',
	    'street1' => '20312 Gramercy Place',
	    'city' => 'Torrance',
	    'state' => 'CA',
	    'zip' => '90501',
	    'phone' => '999-123-4567'
	  ),
	  'parcel' => array(
	    'length' => 9,
	    'width' => 6,
	    'height' => 2,
	    'weight' => 10
	  )
	));
	
	echo $shipment;

?>
```

the file I include includes the library and has the auth key for the test environment - nothing crazy

**Comment by MattSich** [comment]
@gsinkin so I get a 500 internal server error after 2 minutes. I guess that's a php timeout default or something

**Comment by MattSich** [comment]
@gsinkin it looks like it hangs up like that 40% of the time

**Comment by dangrossman** [comment]
Check your PHP error log to see the cause of the 500 error. It might give you a clue on *what* is timing out.

**Comment by victoryftw** [comment]
This is quite strange. I'm unable to recreate this problem on my machine; every attempt to run the code segment you provided successfully completes in ~2 seconds. What version of PHP are you using? If we're using different versions, that may be a factor. Also, please confirm that you're using the most up-to-date version of the client library (though I'm sure you already have).

```

**Comment by MattSich** [comment]
@victoryftw version 5.4.42. Checking the logs now

**Comment by MattSich** [comment]
@victoryftw ok this is very weird. cURL has the same issue. This is running on Dreamhost on one one their cheap hosting services... maybe they have something weird. Been trying to get the error logging but their docs aren't super clear on how to turn it on lol

**Comment by MattSich** [comment]
@victoryftw it works so nice on my local terminal. =( it's definitely something with the hosting service.

**Comment by victoryftw** [comment]
@MattSich yeah that sound like an issue with the hosting service then. Its pretty unacceptable that it times out 40% of the time though.

**Comment by MattSich** [comment]
@victoryftw no way. Just upgraded to 5.6 and it's working fine

**Comment by victoryftw** [comment]
@MattSich Really? That's very strange. I guess it's good as long as it works now! I wonder if Dreamhost has some issue with older PHP versions?

**Comment by MattSich** [comment]
@victoryftw scratch that... I guess I just got lucky a few times haha

**Comment by MattSich** [comment]
@victoryftw definitely feels like it's less constant now though... I wish I could get to that error log more easily

**Comment by victoryftw** [comment]
@MattSich Very strange. It must have to do with some Dreamhost configuration/system issue. If the answer doesn't present itself quickly I'd recommend reaching out to their support to see if this is a recurring issue.

**Comment by att14** [comment]
@MattSich lets move this to the support ticket you have open unless you think the information you receive will be useful for other users of the client. Otherwise, please update us on your findings.

**Comment by MattSich** [comment]
@att14 so I set up godaddy hosting and transferred my API and it's working perfectly now. I'm not sure what the issue is but I definitely think this could help someone who runs into this issue with dreamhost.

**Comment by att14** [comment]
Yup, thanks for updating. Let us know if you have any other issues.

**Comment by malafaka1** [comment]
I’m new here can any who teach me how to use the API n which 1 to use?
malafaka1@yahoo.com
