### ISSUE TITLE
No rates option for batch before buying

### ISSUE THREAD

**Issue by MattSich** [EasyPost/easypost-php#21]
So I'm able to create a batch with some shipments but I want to know the price before buying. If I create a shipment with multiple packages like in your batch example, I get an empty rates array. Likewise, if I retrieve the shipment id of a package in the batch, it gives me an empty rate array. 
How do I know how much the batch will cost before I hit buy() ?

**Comment by att14** [comment]
The purchase of a Batch is not designed to have insight into this. It is for shipments you know you are going to buy at the same service no matter what. If you want to buy shipments at a different service level or rate you need to create the shipments before hand and then use EasyPost::Batch#add_shipments to accomplish this.
