### ISSUE TITLE
blank to_address field?

### ISSUE THREAD

**Issue by raafirivero** [EasyPost/easypost-php#22]
in creating several labels I'm having an issue where the name of the addressee in Ship To: comes up blank but I'm still able to create a label. Has anyone else come across this issue? 
![f4801e9622b243728f99444b1dca95f5](https://cloud.githubusercontent.com/assets/6245124/10873992/d483cb34-80ea-11e5-9120-d6a24d1aeed4.png)

**Comment by att14** [comment]
@raafirivero If you email support@easypost.com with your email and the shipment id, we will be able to help you with this issue better.
