### ISSUE TITLE
[Feat]:  Add status_detail field to TrackingDetail resource

### ISSUE THREAD

**Issue by aaronjewell** [EasyPost/easypost-php#274]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

This field is available in Tracker resource endpoints and webhooks, but not available in the library. See API payload here for example:

https://www.easypost.com/docs/api#create-a-tracker

**Comment by jchen293** [comment]
Hello @aaronjewell, thank you for bringing this issue to our attention. I can confirm that it is valid, and I have created internal tasks to address it. A patch for the client libraries will be made available soon, along with an update to the API documentation.

Thanks for choosing EasyPost 😄

**Comment by aaronjewell** [comment]
Thank you much!

**Comment by Justintime50** [comment]
@aaronjewell I tossed up a PR to address this; however, PHP being a dynamic language shouldn't need this addition for it to work. I'd like to get more info on the actual ask here. Was the concern that `status_detail` was missing from the list of properties of the class in the class docstring? If so, this PR will address that. If there was more to it, I'd love to hear about that so we can address this properly.

**Comment by aaronjewell** [comment]
> @aaronjewell I tossed up a PR to address this; however, PHP being a dynamic language shouldn't need this addition for it to work. I'd like to get more info on the actual ask here. Was the concern that `status_detail` was missing from the list of properties of the class in the class docstring? If so, this PR will address that. If there was more to it, I'd love to hear about that so we can address this properly.


Docstring is all that is needed for our uses. Wanted to confirm it is an intentional property, and the docstring satisifies our static analysis checks via PHPStan. There is a small typo on the Parcel's weight property as well, but we are able to work around it.

Thank you for patching this so quickly! 🚀

**Comment by aaronjewell** [comment]
If you are open to contributions, we are happy to put up PR's in the future, but did not see contribution guidelines.

**Comment by Justintime50** [comment]
More than happy to have contributions, if you'd like to put one up to fix the typo you found we can take a look! Our contributing guidelines can be found here: https://github.com/EasyPost/.github/blob/main/CONTRIBUTING.md
