### ISSUE TITLE
Call to undefined function EasyPost\mb_detect_encoding()

### ISSUE THREAD

**Issue by jeremyhodges** [EasyPost/easypost-php#28]
Installed library via composer. Running on CentOS 7 and I get the following error when trying to create a shipment...

```
Fatal error: Call to undefined function EasyPost\mb_detect_encoding() in /var/www/html/forecast/vendor/easypost/easypost-php/lib/EasyPost/Requestor.php on line 23
```

**Comment by dangrossman** [comment]
Your system is missing the PHP multibyte string library. 

`yum install php-mbstring`

**Comment by jeremyhodges** [comment]
Excellent. Thank you @dangrossman
