### ISSUE TITLE
Upgrade guide for 2.1 to 3.0?

### ISSUE THREAD

**Issue by hackel** [EasyPost/easypost-php#30]
Could you please provide an upgrade guide for 2.1 to 3.0?  Assuming 3.0 is a major version with incompatible API changes, as the version number suggests, this is kind of important.  If you've deviated from the standard semver model (which I don't recommend!), and the API is actually the same, then you should also state that.  Leaving it as a mystery for the developer is not very friendly.  I don't want to have to compare your commit history to figure this out!

Edit: just noticed you do have a CHANGELOG which would seem to indicate that nothing has changed to warrant a new major version.

**Comment by att14** [comment]
This change is quite minor involving retrieving shipments by their tracking code. Previously, the id of the shipment would remain the tracking code. We fixed this issue by updating the id to be the EasyPost id. You should be able to upgrade with no issues unless you rely on this behavior.
