### ISSUE TITLE
[Bug]: Timezone is changed and not changed back

### ISSUE THREAD

**Issue by robgridley** [EasyPost/easypost-php#310]
### Software Version

6.8.1

### Language Version

8.1.11

### Operating System

Ubuntu

### What happened?

Your client is forcing the timezone to UTC to get a UTC timestamp in microseconds, but you're not switching it back. Line [186](https://github.com/EasyPost/easypost-php/blob/5655532be2373865cdca567e770ebf6c44f83155/lib/EasyPost/Http/Requestor.php#L186) in lib/EasyPost/Http/Requestor.php.

### What was expected?

As of PHP 7.1 the built-in [DateTime class](https://www.php.net/manual/en/class.datetime.php) supports microseconds. You can create a new DateTime instance, change the timezone of the instance to UTC, then format it as a timestamp. You could also store the current timezone, set it to UTC, call microtime(), then change the timezone back.

**Comment by robgridley** [comment]
By using date_default_timezone_set(), you're not just changing the timezone for your library, you're changing the timezone for my application.

**Comment by robgridley** [comment]
Thanks! For now I'm storing my app's timezone and switching it back after every API call.

**Comment by Justintime50** [comment]
Mind double-checking my PR to make sure it's along the lines of what you had in mind?

**Comment by Justintime50** [comment]
Perfect, we'll get this released shortly. Thanks again for reporting this!

**Comment by NHZEX** [comment]
The current fix did not completely resolve this issue. During the process of restoring the time zone, there are HTTP requests (IO operations) involved. In the 'Fiber' or 'Swoole' runtime environment, any IO operation will cause coroutine switching. The current global methods will contaminate the entire process space. Please use the 'DateTime' object to safely resolve this problem.

> I used a translation tool to translate this error report. Please let me know if there are any inaccuracies or if you need any further clarification.

**Comment by Justintime50** [comment]
This should be fixed for good with the release of v6.9.1. Let us know if that's not the case!
