### ISSUE TITLE
verify without verify_strict (and vice_versa) generates a notice

### ISSUE THREAD

**Issue by loglow** [EasyPost/easypost-php#32]
### When creating an address:

If `verify` is specified but not `verify_strict` (or vice versa) a notice will be generated like:

**Notice:** Undefined index: verify_strict in **/lib/EasyPost/Address.php** on line 56

This is because both variables are being referenced even if only one of them is set.

### Temporary workarounds:

- Specify `'verify_strict' => false` when creating an address
- Change to `@$verify_strict` in the source to silence the notice

**Comment by victoryftw** [comment]
We've just released a new version of the PHP client library (3.1.3) that removes this warning. You are correct that it had to do with both `verify` and `verify_strict` being referenced in the code even though only one of them is defined.

Sorry for the delay on getting this resolved.

**Comment by loglow** [comment]
Hey, cool :)
