### ISSUE TITLE
Invalid File Type error when attempting to get label

### ISSUE THREAD

**Issue by ottaz** [EasyPost/easypost-php#34]
The label function in the Shipment class builds a url in the form,
```
https://api.easypost.com/v2/shipments/shp_0fe9bed4044d44eea7f293094ff809cd/label
```
and then expects the file format as a parameter in the form of an array
```php
['file_format' => 'pdf']
```
When I try to request a specific file format using this method, I get back an invalid file type error. Note that this functionality used to work just fine and it is only recently this issue began to happen.

I have reproduced this using an API client just to demonstrate visibility of the error.

![eplabelissue1](https://cloud.githubusercontent.com/assets/5402601/14262114/d787aa92-fa81-11e5-8c6e-9b6585ef0c03.gif)

Please advise, perhaps I'm just missing something?

**Comment by att14** [comment]
Unfortunately the HTTP method for `/shipments/:id/label` is not correct for what it actually does. It should be a POST because it creates the additional label. When you try to convert to PDF from PNG, but the PDF already exists it returns this error.
