### ISSUE TITLE
Only one carrier_account_id can be supplied when purchasing a shipment without rating.

### ISSUE THREAD

**Issue by MattSich** [EasyPost/easypost-php#35]
I had my web app working perfectly and now it's failing... did something change? 
I'm creating a batch and trying to purchase it. My batch is being created like this: 

> 
> $batch = \EasyPost\Batch::create(
> 		array(
> 			'shipment' => $arrayOfShipments
> 		)
> 	);

$arrayOfShipments is an array of arrays being added like this:

> 
> array_push($arrayOfShipments, array(
> 		  'to_address' => $toAddress,
> 		  'from_address' => $fromAddress,
> 		  'parcel' => $parcelToUse,
> 		  'carrier' => 'USPS',
> 		  'service' => 'Priority'
> 		));

The error triggers when I create an actual shipment object with one of those pieces like this:

> $shipment = \EasyPost\Shipment::create(array(
> 		  'to_address' => $toAddress,
> 		  'from_address' => $fromAddress,
> 		  'parcel' => $parcelToUse,
> 		  'carrier' => 'USPS',
> 		  'service' => 'Priority'
> 		));
> 

here is the full error that I get:

<br />
<b>Fatal error</b>:  Uncaught exception 'EasyPost\Error' with message 'Only one carrier_account_id can be supplied when purchasing a shipment without rating.' in /home/****/public_html/PAPI/EasyPost/Requestor.php:203
Stack trace:
#0 /home/****/public_html/PAPI/EasyPost/Requestor.php(193): EasyPost\Requestor-&gt;handleApiError('{&quot;error&quot;:{&quot;code...', 422, Array)
#1 /home/****/public_html/PAPI/EasyPost/Requestor.php(89): EasyPost\Requestor-&gt;_interpretResponse('{&quot;error&quot;:{&quot;code...', 422)
#2 /home/****/public_html/PAPI/EasyPost/Resource.php(94): EasyPost\Requestor-&gt;request('post', '/shipments', Array)
#3 /home/****/public_html/PAPI/EasyPost/Shipment.php(30): EasyPost\Resource::_create('EasyPost\\Shipme...', Array, NULL)
#4 /home/****/public_html/PAPI/tests/shippingTest.php(120): EasyPost\Shipment::create(Array)
#5 {main}
  thrown in <b>/home/****/public_html/PAPI/EasyPost/Requestor.php</b> on line <b>203</b><br />

**Comment by att14** [comment]
When creating a Shipment outside of a batch the `carrier` and `service` keys should not be included. They are used for purchasing a shipment without rating and the `carrier_accounts` attribute must be specified as one id.

If you remove the `carrier` and `service` keys from your request it will work as expected. Please email support@easypost.com if you have any additional questions.
