### ISSUE TITLE
Generating the PDF version of postage label will crop the label

### ISSUE THREAD

**Issue by claw68** [EasyPost/easypost-php#40]
```
$shipment = \EasyPost\Shipment::create(
	Array(
		'from_address'=> $from,
		'to_address'=> $to,
		'parcel'=> $parcel,
		'carrier_accounts'=> $carrier
	)
);
		
$ship_json = $shipment->buy(Array(
	'rate' => $shipment->lowest_rate(
		Array('DHLExpress'),
		Array('ExpressWorldwideECX')
	)
));

$ship_json->label(Array('file_format' => 'PDF'));
```

This code will generate a pdf with a blank first page and cropped second page. How will I resolve this issue?

**Comment by att14** [comment]
Label conversion only works for 4x6 labels. Since DHL Express labels are 4x12 you'll need to use the `label_format` option to get a PDF initially.

**Comment by claw68** [comment]
Hi, using the label_format will generate a pdf on test with addresses:

From address:
> EasyPost, Inc
> TEST LABEL
> 164 Townsend
> 94107 SAN FRANCISCO CA
> United States Of America

To address:
> TEST CO
> Test Person
> 346 Test Street
> 94609  OAKLAND CA
> United States Of America

Regardless of the addresses I specify. Is this intended?

**Comment by att14** [comment]
`label_format` determines the file format of the generated label. You can specify one of the following: "PNG", "PDF", "ZPL", and "EPL2".

**Comment by claw68** [comment]
I understand. What I'm trying to say is that regardless of what I input to $from and $to to this snippet:

```
$shipment = \EasyPost\Shipment::create(
	Array(
		'from_address'=> $from,
		'to_address'=> $to,
		'parcel'=> $parcel,
		'carrier_accounts'=> $carrier,
		'options' => array('label_format' => 'PDF', 'currency' => 'EUR')
	)
);

return $shipment->buy(Array(
	'rate' => $shipment->lowest_rate(
		Array('DHLExpress'),
		Array('ExpressWorldwideECX')
	)
));
```

Will return a pdf that contains the addresses:

From
> EasyPost, Inc
> TEST LABEL
> 164 Townsend
> 94107 SAN FRANCISCO CA
> United States Of America

To:
> TEST CO
> Test Person
> 346 Test Street
> 94609 OAKLAND CA
> United States Of America

This issue is not present when generating it as PNG.

**Comment by att14** [comment]
What is the issue and what are you expecting to see?

**Comment by claw68** [comment]
For example if I specify:
```
$from = Array(
	'name' => "Franz Andrew",
	'company' => "Company",
	'street1' => "Narva mnt 7d-B",
	'street2' => "",
	'city' => "Tallinn",
	'state' => "",
	'zip' => "10117",
	'country' => "EE",
	'phone' => "123456",
	'email' => "email@email.com"
);
```

I am expecting to see "Franz Andrew Company Narva mnt 7d-B" on the generated PDF instead of "EasyPost Inc. TEST LABEL 164...".

This is only happens if I specify the label_format as PDF, in PNG, the addresses changes as expected.

**Comment by att14** [comment]
I'm sorry I don't fully understand the problem. `label_format` and the `Address` objects have nothing to do with each other. Can you email support@easypost.com so I can ask for your account details?

**Comment by claw68** [comment]
Try generating a postage label with label_format = pdf. So you will understand the problem.

**Comment by claw68** [comment]
I already sent an email to support@easypost.com. Attached are the PNG with the expected output and a PDF that contains the incorrect output when using label_format = pdf.

**Comment by dangrossman** [comment]
FYI, your problem seems well-specified to me. Hope you can get help with it.

**Comment by claw68** [comment]
Thanks Dan, I tried explaining it the best I can - repeatedly. I provided examples that are ready to run with small modifications to replicate the problem. I'm still baffled on how will I explain this issue better. I guess replicating it on their side is the only way for them to understand the problem.

**Comment by gsinkin** [comment]
Hey guys,

I'm throwing @att14 under the bus on this one. I built the DHL Express integration with EasyPost and can explain what is going on here. The "issue" you are seeing is DHL Express specific. The DHL Express test environment/API returns labels that are visually identical to their production labels. As such, to keep customers from accidentally shipping test labels, EasyPost returns a canned PDF label in test mode. For test ZPL labels, we strip out the barcode, and for PNGs, we stamp VOID on the label.

The reason others on the team were not able to reproduce the issue is because this is DHL Express specific.

I hope that clears things up.

Thanks,

Gabe

**Comment by att14** [comment]
![Under the Bus](https://media.giphy.com/media/Wyl6b64NUTTiw/giphy.gif)

**Comment by claw68** [comment]
Hi Gabe,

Thank you for clarifying. To confirm, this "issue" should not be present on the production environment, correct?

**Comment by gsinkin** [comment]
You got it. This is not an issue in production. If it were, we'd be receiving truckloads of DHL Express parcels here at EasyPost (our old office, anyway).

You can try purchasing a label in production and refunding it. DHL Express labels are bill on scan, so you will only be billed the 0.03 USD EasyPost label fee (refunded on refund request).

Thanks,

Gabe

**Comment by claw68** [comment]
Alright. Thank you so much Andrew and Gabe!

**Comment by claw68** [comment]
Hi, sorry hijacking this thread to ask a question because I can't get an answer somewhere else. How long will the DHL Express waybills generated via Easypost will be valid if it's not scheduled for pick up for a long time?

**Comment by gsinkin** [comment]
Great question. Let me contact DHL Express and get back to you.

**Comment by gsinkin** [comment]
Ok, here's how things work. The DHL Express system purges shipment information after 10 days. That means you have 10 days to use the label. However, if you expect to use the label more than 10 days from label creation, you should set the shipment.option.label_date to the estimated shipping date. If the label_date is more than 10 days out, we pass a special shipment option to DHL Express to tell them to retain the shipment info for up to 90 days.

I hope that clears things up.

Thanks,

Gabe

**Comment by gsinkin** [comment]
One caveat. The Paperless Trading option is not available for shipments more than 10 days out. If you purchase a label and do not ship it for more than 10 days, you will need to provide the commercial invoice separately (in the shipment.forms field).

**Comment by claw68** [comment]
Hi Gabe,

Thank you so much for clearing this up. According to DHL Express, SpecialServiceType - PW will extend this 90 days to up to 24months. Is this supported as well?

**Comment by claw68** [comment]
Sorry, I have limited knowledge about commercial invoices, I would have to ask, do we need to send this via shipment.forms to use the label?

**Comment by gsinkin** [comment]
Hi,

If you ship the parcel after 10 days, you will need to print the invoice in the shipment.forms field and provide the printed commercial invoice along with the parcel.

I will investigate the PW option. However, why would you want to hold on to a label for up to 24 months? This seems like a very bad idea.

Thanks,

Gabe

**Comment by claw68** [comment]
Hi,

I tried passing label_date with the values 1-4 days from now and it returns both rate and label_pdf_url which is intended.

However, if I pass a date that is >= 5 days from current date, it doesn't return rate nor label_pdf_url, is this intended? 

What should I do in order to get the rate and label_pdf_url for >= 5 label_date?

Thanks

**Comment by mwaldt** [comment]
Hi,

If you can direct any support requests to support@easypost.com I will be able to better help you resolve them there. Please be sure to specify your account email as well as any object identifiers to help us troubleshoot.

Cheers,
