### ISSUE TITLE
label_date not correct on UPS Mail Innovations International

### ISSUE THREAD

**Issue by osmaanshah** [EasyPost/easypost-php#42]
Setting the options->label_date does not appear to work for UPS Mail Innovations international shipping.  The date printed on the label always shows the date the label was generated, not the date provided in the label_date option.  This value is working for other carriers we use (ex:  USPS).

**Comment by att14** [comment]
Hey @osmaanshah,

Questions about specific carrier business rules are easier to answer through email so I can ask for shipment ids and your email address. If you could email support@easypost.com I'd be happy to troubleshoot this issue for you.

Cheers.
