### ISSUE TITLE
Request for Address Verification Level Option

### ISSUE THREAD

**Issue by claw68** [EasyPost/easypost-php#43]
We are shipping to United Kingdom and the address verification level is set to Unit by default.

The problem is that we are having a lot of false negatives because the verification is "too strict".

Can we have a parameter in Address Object that allows setting the verification level

Example:

```php
$address = Array(
"street1" => "417 Montgomery Street",
"street2" => "FL 5",
"city"    => "SAN FRANCISCO",
"zip"     => "94104-110",
"country" => 'US',
"verify" => Array('delivery'),
"verify_level" => "House" //or Unit, Street, City
);
```

**Comment by DorianGray** [comment]
Sorry for the very late response on this. Something similar is planned and on our roadmap for this year. In fact, I've already reworked the internals to allow configuration of several aspects of the verification process.

**Comment by claw68** [comment]
Thanks @DorianGray for the update. Please update this thread for the developments.

**Comment by Justintime50** [comment]
@claw68 at the API level, this is not supported. You can check out what the validation level on each country is here: https://www.easypost.com/docs/address-verification-by-country or the verification object here: https://www.easypost.com/docs/api#verifications-object. As the API does not support this functionality, adding it to the client library here will have no effect.
