### ISSUE TITLE
Rate IDs not found

### ISSUE THREAD

**Issue by neutt22** [EasyPost/easypost-php#44]
I'm trying to get the rate ID of the shipment I made:

```
// Get rates for this vendor
$shipment = \EasyPost\Shipment::create($shipment_params);

// Save for future purchase
session()->put('shipment_id', $shipment->id);
```

But when I'm retrieving the shipment object, some rate IDs are not found in the object anymore

```
// Retrieve the shipment
$shipment = \EasyPost\Shipment::retrieve(session()->get('shipment_id'));
```

Result:

Shipment ID: shp_94b41cdc3a214753804ff81077d6f7a1
Rate ID: rate_a4bba263b1374fe684151bffaa8d1f03 (Found while retrieving shipment)
Rate ID: rate_4ebcfa4ca339457d9f1f66d378a2663f (NOT Found while retrieving shipment)

Cheers

**Comment by neutt22** [comment]
Hence I get this error when buying using rate ID from retrieved shipment object: Hence I get this issue when buying rates from the shipment: SHIPMENT.MISSING_RATE

**Comment by att14** [comment]
rate_4ebcfa4ca339457d9f1f66d378a2663f belongs to shp_5f639a66626f40938079d0171d52fdd2, so you will not see it when retrieving shp_94b41cdc3a214753804ff81077d6f7a1

**Comment by neutt22** [comment]
Thanks you guys! It was solved i just missed to comment the day i saw your reply.

Btw, how long do you keep test shipment and rate ids?

**Comment by att14** [comment]
There currently is no retention policy, so indefinitely. This is something we may revisit in the future, but we will notify customers beforehand.
