### ISSUE TITLE
Custom Items - description field does not allow accented characters

### ISSUE THREAD

**Issue by osmaanshah** [EasyPost/easypost-php#45]
We are receiving "Invalid Product Description" when an accented character exists in the Custom Item 'description' field.   Not sure if this is something that you want to support; however, just wanted to make sure you were aware.

**Comment by att14** [comment]
The error comes from the carrier directly. We try to do transliteration of accented characters where possible. Can you provide me with a shipment id? Or email support@easypost.com and we can investigate.

**Comment by mwaldt** [comment]
Since there has been no movement on this I am going to resolve the issue. If you are continuing to experience this reach out to support@easypost.com for assistance.
