### ISSUE TITLE
ZPL file output only 200 DPI

### ISSUE THREAD

**Issue by dmo9** [EasyPost/easypost-php#48]
I require batch shipping and ZPL but the zpl output seems to be fixed at 200dpi - this causes scaling issues on higher resolution printers such as my 300dpi Zebra.

Initially I had the idea to write a script to edit the zpl itself but it appears to be created in binary instead of purely ZPL commands. Are there any alternatives or workarounds for batch printing?

On batch printing, pdf comes out  in what appears to be for an inkjet, epl2 is also in binary, and png does not seem to be an option for batches.

**Comment by att14** [comment]
Native ZPLs from EasyPost are always 203dpi. Most 300dpi printers can be configured to use 203dpi. What printer are you using?

**Comment by dmo9** [comment]
Boy that would be awesome if I could! I have a zebra TLP3844-Z. I have not figured out how  or if I can adjust the resolution settings for it yet.

**Comment by dmo9** [comment]
It is not possible to convert from 200 to 300 on any printers. Here are the options from zebra:

https://www.zebra.com/us/en/support-downloads/knowledge-articles/format-convert-resolution-conversion-configuration.html

**Comment by tahseenarticle** [comment]
I will like to see 300 dpi as well. The problem is all over internal transportation ZPL labels are written in 300dpi. So we can not change the setting of the printers.

**Comment by att14** [comment]
The best option you have is to use `label_format` PNG and then convert to ZPL using our conversion api: https://www.easypost.com/docs/api#convert-the-label-format-of-a-shipment

**Comment by dmo9** [comment]
The conversion is also 200dpi so that doesn't work

**Comment by att14** [comment]
Yup, looks like you are correct. I did some research and found some resources that could help here. We spoke internally about supporting some sort of conversion script our customers could run.

The official programming [guide](https://support.zebra.com/cpws/docs/zpl/zpl_manual.pdf) has documentation on how to convert from 200->300 using the [Zebra Basic Interpreter](http://www.zebra.com/zbi) starting on page 604 titled DPI Conversion Program.

This should be relatively easy to port to another language. We will add something like this to our backlog, but in the meantime this could help you with your issue.

**Comment by brprigge** [comment]
Reviving this issue.  Any progress here?

**Comment by Justintime50** [comment]
@brprigge @dmo9 @tahseenarticle the API provides labels at 200dpi, there is no way with our without the client libraries to alter this item.
