### ISSUE TITLE
Timeout settings

### ISSUE THREAD

**Issue by ghola** [EasyPost/easypost-php#5]
The library should allow it's users to control the timeout settings. 80 seconds for a request (the default) is unacceptable. Imagine that an operation like the label purchase needs to be done within a database transaction in order to make sure it is not purchased twice, and keeping the transaction open for 80 seconds is not cool.

**Comment by briedis** [comment]
Please fix this. There is already a pull request with a fix.

**Comment by sawyer** [comment]
We're going to remove those values from being explicitly set in c43f3c6.

We consider the default values acceptable, and are in full support of a community fork if there's a solid need for setting timeout values on a per request basis.

**Comment by briedis** [comment]
Default value is 300 seconds for CURLOPT_CONNECTTIMEOUT and indefinite for CURLOPT_TIMEOUT. In which live production environment could this be acceptable? Maybe it would be possible to optionally set own curl options?
