### ISSUE TITLE
autoloader?

### ISSUE THREAD

**Issue by treii28** [EasyPost/easypost-php#55]
Suggestion, replace or otherwise supplement the 'lib/easypost.php' with an autoloader (e.g. lib/autoloader.php)

`
    
    class EasyPostAutoloader {
        static public function loader($className) {
            if(class_exists($className)) {
                return true;
            }
    
            // replace the namespace with the subdirectory path /classes
            $easypostDir = realpath(__DIR__);
            $classFn = str_replace("\\", '/', $className);
            $filename = $easypostDir . "/" . $classFn . ".php";
            $fExists = file_Exists($filename);
            if ($fExists) {
                include_once($filename);
                if (class_exists($className)) {
                    return TRUE;
                }
            }
            return FALSE;
        }
    }
    spl_autoload_register('EasyPostAutoloader::loader');
`

**Comment by treii28** [comment]
Then you only need include the autoloader and can utilize the 'use' command if desired:

`
    
    require_once("lib/autoloader.php");
    
    use EasyPost\EasyPostObject;
    
    $epo = new EasyPostObject(); // shortname from use above
    // or
    $addr = new EasyPost\Address();
`

**Comment by browner12** [comment]
do you not use your Composer autoloader?

**Comment by treii28** [comment]
Um ok, but your sample/example suggests the first line being:
require_once("/path/to/lib/easypost.php");
(which is a file full of requires and zero DI functionality. Regardless what libs you might be  using, all are loaded at once.)
 So why not supply the independent loader with the same functionality?

**Comment by browner12** [comment]
my bad, now I remember.

use one or the other.  if you use Composer, great, you get your free autoloader and don't need to manually require `easypost.php`.

if you don't use Composer or another autoloader, you have to manually do the require.

**Comment by Justintime50** [comment]
@treii28 - @browner12 is correct, you'll either use one or the other. Either you'll manually require the file (eg: `require_once("/path/to/lib/easypost.php");`) or you can use Composer (recommended) which will then allow you to do something like `use \EasyPost\EasyPost;`.

For an example of using composer, you can check out https://github.com/Justintime50/easypost-ui where [EasyPost is used with Composer](https://github.com/Justintime50/easypost-ui/blob/master/src/composer.json#L12) and [you can see that `use` is being used here](https://github.com/Justintime50/easypost-ui/blob/master/src/app/Http/Controllers/AddressController.php#L6-L7).

The [README](https://github.com/EasyPost/easypost-php/blob/master/README.md) for this project has been recently updated with some clarified installation/setup instructions that may be beneficial to check. I hope this helps!
