### ISSUE TITLE
Readme inconsistencies

### ISSUE THREAD

**Issue by PeteFromSales** [EasyPost/easypost-php#56]
1. The README implies that this library should only be loaded via a custom repository URL, via adding an entry into the `composer.json` `"repositories"` field. However, it's been submitted to packagist.org, so this shouldn't be necessary anymore.

2. The README implies that we should use version 3.0, but the current library is at version 3.4.0. 

Is the README just out of date? Or should it continue to be followed?

**Comment by browner12** [comment]
version `~3.0` is fine, since it will allow updating the minor version all the way up to 3.4.x

**Comment by PeteFromSales** [comment]
Thanks, @browner12 . Is there a reason to continue using the VCS method of adding to composer over https://packagist.org/packages/easypost/easypost-php?

**Comment by browner12** [comment]
probably not, but maybe the maintainers will have something to say about it.

**Comment by Justintime50** [comment]
@jontsai with my recent README changes, this could now be closed as the installation instructions have been clarified.

**Comment by jontsai** [comment]
Resolved by #76, #77
