### ISSUE TITLE
Prepopulate all the carrier services

### ISSUE THREAD

**Issue by orso081980** [EasyPost/easypost-php#60]
Is there any way to pre-populate all the carrier services, as soon as you lunch the app, before doing any purchases or initiate the process?

For example:

->carrier::services

will return an array of all the shipment available after the API call

**Comment by att14** [comment]
That is currently not possible and is quite difficult for a variety of carriers that have dynamic or temporal service levels. Is there a specific carrier you are interested in?

**Comment by orso081980** [comment]
Canada post and purolator

**Comment by orso081980** [comment]
It could be a super cool feature by the way.. what about adding a fake shipment? I developed a backend interface where you can add your API key and it will auto-populate the service for you
