### ISSUE TITLE
"Undefined variable: v" when deleting carrier account.

### ISSUE THREAD

**Issue by programmerkev** [EasyPost/easypost-php#61]
I'm getting an exception, "Undefined variable: v", when trying to do this:

`\EasyPost\CarrierAccount::retrieve("ca_...")->delete();`

It looks like there is a bug in the __unset method of EasyPostObject.php. On line 123 the value of $v is being assigned. But I don't see $v being defined anywhere in that method.

https://github.com/EasyPost/easypost-php/blob/517b6205c9316d67da2241345fa9d52b87ddedf4/lib/EasyPost/EasyPostObject.php#L123

**Comment by roshan2806** [comment]
I'm getting same kind of error.

Can anyone please give the solution for above issue.

Thank you.
