### ISSUE TITLE
Fatal error: Cannot use 'Object' as class name

### ISSUE THREAD

**Issue by loglow** [EasyPost/easypost-php#72]
The server hosting my PHP code was recently updated, and I began getting fatal errors about not being able to use "Object" as a class name.

I changed the class name to "EPObject" as well as all references to it elsewhere in the code, and the library appears to now work again.

**Comment by Justintime50** [comment]
@loglow you must have been using an old version of the client library as this has been fixed since v3.4.0 (11/30/17). It is called `EasyPostObject` now.
