### ISSUE TITLE
How to serialize EasyPost objects for sending to web client

### ISSUE THREAD

**Issue by RyanEwen** [EasyPost/easypost-php#90]
Hi there,

I am having a hard time figuring out how I would pass shipment data or rate data from PHP to elsewhere as JSON, as something like `json_encode($shipment);` ends up empty due to all of the `EasyPost\Shipment` properties being protected.

How are these objects supposed to be interacted with in cases like this? Is there a method to serialize them that I am not seeing? XDebug isn't showing me the protected properties so it's hard to dig around myself.

**Comment by Justintime50** [comment]
@RyanEwen can you elaborate on what exactly you'd like to do? The response will already be returned in JSON if you use this PHP client library, there is not reason to encode it again. You'd interact with the object like any other, for example, if you'd like to only print the shipment ID from the response, you could do something like:

```php 
echo $shipment['id'];
```

This would print the shipment ID. You could pull out any piece you need/like or use the entire response (in this case, shipment object).

**Comment by RyanEwen** [comment]
A browser will be requesting the `$shipment` data from my server via HTTP request. However the layer that handles receiving and responding to HTTP requests automatically uses `json_encode` on any data that is returned by the functions that are going to be called. 

Thanks to your input I was able to figure out that I could `return json_decode($shipment)` in my function so that the layer handling the response can include it within a larger object and `json_encode` everything nicely. 

I do find it a bit weird that the EasyPost objects are like this It looks like I would need to decode them any time I want to use them, even if they weren't being used in a HTTP request layer.

**Comment by Justintime50** [comment]
All our client libraries return JSON objects, depending on your needs you may need to decode them or you can use them as is. Glad you were able to figure out something that worked for your needs!
