### ISSUE TITLE
Add @property documentation to response objects

### ISSUE THREAD

**Issue by colorninja** [EasyPost/easypost-php#96]
First of all, thanks for the library.

It would be nice if you can add the expected properties into the response objects. This would help reduce typos for users of the library and allow IDEs to check for properties accessed using the magic get method.

Currently, I get warnings in my IDE when I'm trying to parse the response, because magic methods is not something myself, or the IDEs are fans of:
![Screenshot from 2020-11-16 10-44-39](https://user-images.githubusercontent.com/32983864/99243933-4b623780-27f9-11eb-98a1-d47129390c3a.png)

Adding property tags to the class documentation is a quick solution for that. Modifying the Rate class:
```php
<?php

namespace EasyPost;

/**
 * Class Rate
 * @package EasyPost
 * @property string $rate
 * @property string $service
 * @property string $carrier
 */
class Rate extends EasypostResource
{
    ...
}
```

results in no warnings and autocomplete:
![Screenshot from 2020-11-16 10-46-34](https://user-images.githubusercontent.com/32983864/99244306-cfb4ba80-27f9-11eb-93c8-59451d77fe1b.png)

**Comment by grutherford** [comment]
+1, This would be very welcome, speeds up development and helps avoid bugs!

**Comment by maksymkulia** [comment]
+1, Also getting warnings in my IDE.

**Comment by grutherford** [comment]
I can confirm JetBrains software such as PHPStorm & IntelliJ certainly do.

**Comment by maksymkulia** [comment]
@Justintime50 yeah, same for me, also PHPStorm.

**Comment by Justintime50** [comment]
Good ole PHPStorm, thank you all!

This isn't at the top of our priority list; however, it will probably get worked on in the future. If you'd like to expedite getting this in the repo, we are open to a pull request if anyone is willing to give it a shot.
